% som_hists
%
% Plots a histogram of class labels won for each prototype, arranged in the
% original lattice. This is faster than using subplot, but still slow.
%
% ARGUMENTS:
%   fig -- The figure to plot on (generated by figure)
%
%   win_sums -- An M x C matrix, where the "wins" of the ith prototype are
%               in row i. The histogram for prototype i will be made from
%               row i. This could be, for example, the 1 in C encoding of
%               the class labels of all of the input data vectors that were
%               won by prototype i.
%
%   lattice_dims -- A vector [lattice_width, lattice_height] giving the
%                   dimensions of the SOM lattice.
%
% SIDE EFFECTS:
%   This will plot onto the passed in figure handle.
%
% Implemented by Jesse Hellemn at Rice University, Fall 2016
function som_hists(fig, win_sums, lattice_dims)
    nRows = lattice_dims(1);
    nCols = lattice_dims(2);
    figure(fig);
    hold on;

    % Axes and titles
    set(gca, 'XTick', 1:nRows);
    set(gca, 'YTick', 1:nCols);
    xlabel('Prototype Column', 'fontsize', 16);
    ylabel('Prototype Row', 'fontsize', 16);

    % Compute where every box should go
    max_height = max(max(win_sums));
    gaxes = gca;
    panel = uipanel('Parent', fig, 'Units', 'normal', ...
        'Position', gaxes.Position);
    w = 0.9 / nCols; % width of every box
    h = 0.9 / nRows; % height of every box
    of_grid = @(i) [ceil(i / nRows), ...
                                mod(i, nRows) + nRows*(mod(i, nRows)==0)];

    % Draw every box in the right position                        
    for i = 1:size(win_sums, 1)
        if sum(win_sums(i,:)) > 0
            coord = of_grid(i);
            ax = axes('units', 'norm', 'Parent', panel, 'pos', ...
                    [(coord(1) - 1) / nCols, (coord(2) - 1) / nRows, w, h]);
            bar(win_sums(i, :), 'parent', ax)
            axis([1, size(win_sums, 2), 0, max_height])
            axis off
        end
    end

end
